name             "chef-hat"
maintainer       "Michal Palys-Dudek"
maintainer_email "michal@michaldudek.pl"
description      "What's a Chef without their hat? This is a Chef Cookbook with few recipes I use often."
version          "0.1.0"